[package]
name = "tetris"
version = "1.3.0"
authors = ["Joinemm <joinemm@pm.me>", "Alexandria P. <alxpettit@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
ruscii = "0.3.2"
